package com.scalecart.order.controller;

import com.fasterxml.jackson.databind.ObjectMapper;
import com.scalecart.order.dto.CheckoutRequest;
import com.scalecart.order.entity.Order;
import com.scalecart.order.entity.OrderStatus;
import com.scalecart.order.security.JwtService;
import com.scalecart.order.service.OrderService;
import org.junit.jupiter.api.DisplayName;
import org.junit.jupiter.api.Test;
import org.springframework.beans.factory.annotation.Autowired;
import org.springframework.boot.test.autoconfigure.web.servlet.AutoConfigureMockMvc;
import org.springframework.boot.test.autoconfigure.web.servlet.WebMvcTest;
import org.springframework.boot.test.mock.mockito.MockBean;
import org.springframework.http.MediaType;
import org.springframework.test.web.servlet.MockMvc;
import org.springframework.test.util.ReflectionTestUtils;

import java.math.BigDecimal;

import static org.mockito.ArgumentMatchers.*;
import static org.mockito.Mockito.when;
import static org.springframework.test.web.servlet.request.MockMvcRequestBuilders.*;
import static org.springframework.test.web.servlet.result.MockMvcResultMatchers.*;

@WebMvcTest(OrderController.class)
@AutoConfigureMockMvc(addFilters = false)
@DisplayName("OrderController Web Layer Tests")
class OrderControllerTest {

    @Autowired
    private MockMvc mockMvc;

    @Autowired
    private ObjectMapper objectMapper;

    @MockBean
    private OrderService orderService;

    @MockBean
    private JwtService jwtService;

    @Test
    @DisplayName("POST /api/orders/checkout — 201 Created on successful checkout")
    void checkout_Success_Returns201() throws Exception {

        CheckoutRequest request = new CheckoutRequest();
        request.setUserId(1L);
        request.setShippingAddress("123 MG Road, Bangalore");

        Order mockOrder = new Order();

        // id has no setter because it is generated by JPA
        ReflectionTestUtils.setField(mockOrder, "id", 1L);

        mockOrder.setUserId(1L);
        mockOrder.setStatus(OrderStatus.PENDING);
        mockOrder.setTotalAmount(new BigDecimal("80498.00"));

        when(orderService.checkout(eq(1L), anyString()))
                .thenReturn(mockOrder);

        mockMvc.perform(post("/api/orders/checkout")
                        .contentType(MediaType.APPLICATION_JSON)
                        .content(objectMapper.writeValueAsString(request)))
                .andExpect(status().isCreated())
                .andExpect(jsonPath("$.id").value(1))
                .andExpect(jsonPath("$.status").value("PENDING"))
                .andExpect(jsonPath("$.totalAmount").value(80498.00));
    }

    @Test
    @DisplayName("POST /api/orders/checkout — 409 on empty cart")
    void checkout_EmptyCart_Returns409() throws Exception {

        CheckoutRequest request = new CheckoutRequest();
        request.setUserId(1L);
        request.setShippingAddress("123 MG Road");

        when(orderService.checkout(anyLong(), anyString()))
                .thenThrow(new IllegalStateException(
                        "Cannot checkout with an empty cart"));

        mockMvc.perform(post("/api/orders/checkout")
                        .contentType(MediaType.APPLICATION_JSON)
                        .content(objectMapper.writeValueAsString(request)))
                .andExpect(status().isConflict())
                .andExpect(jsonPath("$.error")
                        .value("Business Rule Violation"));
    }

    @Test
    @DisplayName("POST /api/orders/checkout — 400 on missing userId")
    void checkout_MissingUserId_Returns400() throws Exception {

        CheckoutRequest request = new CheckoutRequest();

        // userId is null — @NotNull validation should fail
        request.setShippingAddress("123 MG Road");

        mockMvc.perform(post("/api/orders/checkout")
                        .contentType(MediaType.APPLICATION_JSON)
                        .content(objectMapper.writeValueAsString(request)))
                .andExpect(status().isBadRequest());
    }

    @Test
    @DisplayName("PATCH /api/orders/{id}/cancel — 409 on non-PENDING order")
    void cancelOrder_NonPending_Returns409() throws Exception {

        when(orderService.cancelOrder(anyLong(), anyLong()))
                .thenThrow(new IllegalStateException(
                        "Only PENDING orders can be cancelled. " +
                                "Current status: CONFIRMED"));

        mockMvc.perform(patch("/api/orders/1/cancel")
                        .param("userId", "1"))
                .andExpect(status().isConflict());
    }
}